name: "DT1_ABCDEF_d"

connections:
  mqtt:
    broker_url: "localhost"
    port: 1883
    topics:
    - "test/#"
    - "control"
  mongodb:
    use: no
    url: "mongodb://user:pass@localhost:27017"
    database: "pt"
    collection: "events"

  buffer:
    size: 100

process:
  buffer:
    size: 100
  burn:
    workers: 0
    work: 1000
  file_checkpoints:
    use: no
    interval: 20
    path: "./dump.json"

state:
  max_size_mb: 10

flask:
  port: 5003

migration:
  live:
    rounds: 10

logger:
  level:
    shell: debug
    file: debug
    mongo: debug