apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dev-nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 10.16.11.177
    path: /srv/nfs/exports
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dev-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem