---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.js: |
    db = db.getSiblingDB("pt");
    db.createCollection("events");
    print("pt database and events collection created.");


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          imagePullPolicy: IfNotPresent
          args:
            - "--dbpath"
            - "/data/db"
            - "--bind_ip_all"

          ports:
            - containerPort: 27017

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password

          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              cpu: 150m
              memory: 256Mi

          volumeMounts:
            - name: data
              mountPath: /data/db

            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d/init.js
              subPath: init.js

      volumes:
        - name: data
          emptyDir: {}

        - name: mongo-init
          configMap:
            name: mongo-init
